### ISSUE TITLE
inconsistent element id

### ISSUE THREAD

**Issue by ctownshend** [bricewilson/TypeScript-Getting-Started#2]
Hi, great course but I found an issue. There is an inconsistency between the course video and the source code in github

The index.html element is **scores**, but the JS is looking for "**postedscores**"
I just realised the problem the master branch does not have the id on the element, some of the later branches do however.
You need to add the "postedScores" element to the master branch of index.html
postedScores

    <div class="col-sm-offset-2 col-sm-10" id="scores">
the code in module  "Demo: Adding Type Annotations and Default Parameter Values"
const scoreElement: HTMLElement | null = document.getElementById('postedscores');

**Comment by bricewilson** [comment]
Hey @ctownshend. The master branch contains the code as it exists at the beginning of the course. The other branches contain the code as it exists at the end of the module named after the branch. The "scores" element id exists from the very beginning of the course. I add the "postedScores" id about a minute into the clip you referenced ("Demo: Adding Type Annotations and Default Parameter Values"). Since that clip is part of the module titled "Writing Better Functions with TypeScript", you'll find that ID in the branch with that name (and all subsequent branches). I hope that helps. Thanks for watching!

**Comment by ctownshend** [comment]
Yep, all good, missed that bit of the lesson. Will close
